export {default as bannerImage} from '../../images/banner-image.jpg'
export {default as coffeeimage} from '../../images/Coffee.jpg'
export {default as krispy_cream} from '../../images/Krispy_cream _Doughnuts.jpg'
export {default as hotfood} from '../../images/hotfood.jpg'
export {default as swapandgogas} from '../../images/Swap and Go.webp'
export {default as sodastream} from '../../images/Soda stream Swap.webp'
export {default as Baits} from '../../images/WIndybanks_Logo.webp'
export {default as icebag} from '../../images/ice-bags.jpg'
export {default as cta} from '../../images/cta-image.jpg'
export {default as logo} from '../../images/logo.png'
